eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      
microservices:
  college-service:
    endpoints:
      endpoint:
        save-uri: http://COLLEGE-SERVICE/college/save
  
